### ISSUE TITLE
每次运行api一直都有问题，错误信息如下，希望加一下qq1053347682

### ISSUE THREAD

**Issue by momoyangliu** [TerraceCN/YZULessonHunter#2]
Traceback (most recent call last):
  File "httpx\_transports\default.py", line 61, in map_httpcore_exceptions
  File "httpx\_transports\default.py", line 181, in handle_request
  File "httpcore\_sync\connection_pool.py", line 237, in handle_request
  File "httpcore\_sync\connection.py", line 136, in handle_request
  File "httpcore\_sync\connection.py", line 163, in _open_socket
  File "httpcore\_backends\sync.py", line 144, in open_tcp_stream
  File "contextlib.py", line 131, in __exit__
  File "httpcore\_exceptions.py", line 12, in map_exceptions
httpcore.ConnectTimeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "decaptcha.py", line 22, in decaptcha
  File "httpx\_api.py", line 304, in post
  File "httpx\_api.py", line 100, in request
  File "httpx\_client.py", line 785, in request
  File "httpx\_client.py", line 871, in send
  File "httpx\_client.py", line 907, in _send_handling_auth
  File "httpx\_client.py", line 943, in _send_handling_redirects
  File "httpx\_client.py", line 977, in _send_single_request
  File "httpx\_transports\default.py", line 181, in handle_request
  File "contextlib.py", line 131, in __exit__
  File "httpx\_transports\default.py", line 78, in map_httpcore_exceptions
httpx.ConnectTimeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 49, in <module>
  File "api.py", line 48, in login
  File "decaptcha.py", line 24, in decaptcha
decaptcha.DecaptchaRequestException: 请求验证码识别API时发生错误
程序在运行时发生错误，建议你查看README.txt以寻找解决方案

**Comment by TerraceCN** [comment]
已在新版本中替换为本地模型

**Comment by momoyangliu** [comment]
更新使用了一下，还是有错误信息如下，这个是main.exe的运行结果
Traceback (most recent call last):
  File "httpx\_transports\default.py", line 61, in map_httpcore_exceptions
  File "httpx\_transports\default.py", line 181, in handle_request
  File "httpcore\_sync\connection_pool.py", line 237, in handle_request
  File "httpcore\_sync\connection.py", line 148, in handle_request
  File "httpcore\_sync\http11.py", line 128, in handle_request
  File "httpcore\_sync\http11.py", line 189, in _receive_response
  File "httpcore\_sync\http11.py", line 225, in _receive_event
  File "httpcore\_backends\sync.py", line 61, in read
  File "contextlib.py", line 131, in __exit__
  File "httpcore\_exceptions.py", line 12, in map_exceptions
httpcore.ReadTimeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "api.py", line 38, in login
  File "httpx\_client.py", line 1103, in post
  File "httpx\_client.py", line 785, in request
  File "httpx\_client.py", line 871, in send
  File "httpx\_client.py", line 907, in _send_handling_auth
  File "httpx\_client.py", line 943, in _send_handling_redirects
  File "httpx\_client.py", line 977, in _send_single_request
  File "httpx\_transports\default.py", line 181, in handle_request
  File "contextlib.py", line 131, in __exit__
  File "httpx\_transports\default.py", line 78, in map_httpcore_exceptions
httpx.ReadTimeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 49, in <module>
  File "api.py", line 50, in login
api.URPRequestException: 登录时发生错误
程序在运行时发生错误，建议你查看README以寻找解决方案
//////////
这个是main.py运行结果：
python main.py
Traceback (most recent call last):
  File "D:\lessonhunter\yzulesson-hunter-new\main.py", line 9, in <module>
    from api import URP, URPRequestException
  File "D:\lessonhunter\yzulesson-hunter-new\api.py", line 7, in <module>
    from decaptcha import decaptcha
  File "D:\lessonhunter\yzulesson-hunter-new\decaptcha.py", line 4, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
